### ISSUE TITLE
Do extensive testing on all supported browsers

### ISSUE THREAD

**Issue by sharon-wang** [esse-dev/akita#128]
Before submitting to extension stores in our next release, let's test on all browsers in both WM-provider mode and non-WM provider mode. This is just a reminder to do this testing.

**Comment by vezwork** [comment]
As discussed with @sharon-wang, here's our testing guide:

## User types to test as

- As a monetized person: assigned to @vezwork 
- As a non-monetized person: assigned to @sharon-wang 

## Browsers to test

- Chrome
- Firefox
- Edge

## Things to test

- Behaviour after installing for the first time
- Behaviour after updating to the latest code
- Test clicking links in the popup
- Test that the feedback link points to the correct monetized vs non-monetized survey
- Change popup threshold to 5000 for 5s and ensure it shows up
- verify stats are correct and icon is correct
  - Test iframes '[https://gunnywatcher.itch.io/firsttest](https://gunnywatcher.itch.io/firsttest)' or '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)'
  - Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
  - Test [Twitch.tv](http://twitch.tv) channel
  - Normal website i.e. [github.com](http://github.com)
  - Monetized website i.e. [dev.to](http://dev.to)

**Comment by sharon-wang** [comment]
# Testing as a non-monetized person, without Coil installed unless otherwise stated

- [x] Brave, with Coil installed but no ongoing subscription
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)'
    - [x] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [x] Test [Twitch.tv](http://twitch.tv) channel
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)
- [x] Firefox
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] **Test clicking links in the popup --- ISSUE: https://github.com/esse-dev/akita/issues/139**
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)'
    - [x] **Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ) --- ISSUE: https://github.com/esse-dev/akita/issues/138**
    - [x] **Test [Twitch.tv](http://twitch.tv) channel --- ISSUE: https://github.com/esse-dev/akita/issues/138**
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)
- [x] Edge
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] **Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)' --- ISSUE: https://github.com/esse-dev/akita/issues/140**
    - [x] **Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ) --- ISSUE: https://github.com/esse-dev/akita/issues/138**
    - [x] **Test [Twitch.tv](http://twitch.tv) channel --- ISSUE: https://github.com/esse-dev/akita/issues/138**
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)
- [x] Chrome
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] **Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)' --- ISSUE: https://github.com/esse-dev/akita/issues/140**
    - [x] **Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ) --- ISSUE: https://github.com/esse-dev/akita/issues/138**
    - [x] **Test [Twitch.tv](http://twitch.tv) channel --- ISSUE: https://github.com/esse-dev/akita/issues/138**
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)

**Comment by vezwork** [comment]
# Testing as a monetized person

- [x] Chrome
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] Test iframes '[https://gunnywatcher.itch.io/firsttest](https://gunnywatcher.itch.io/firsttest)' or '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)' **NOT WORKING #140**
    - [x] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [x] Test [Twitch.tv](http://twitch.tv) channel
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to) **NOT WORKING #137**
- [x] Firefox
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] Test iframes '[https://gunnywatcher.itch.io/firsttest](https://gunnywatcher.itch.io/firsttest)' or '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)' **WORKING**
    - [x] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [x] Test [Twitch.tv](http://twitch.tv) channel
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)
- [x] Edge
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] Test iframes '[https://gunnywatcher.itch.io/firsttest](https://gunnywatcher.itch.io/firsttest)' or '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)' **WORKING**
    - [x] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [x] Test [Twitch.tv](http://twitch.tv) channel
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)
